// This file can be auto-generated by Supabase CLI in a real project
// For now, we define them manually based on our schema

export type UserRole = 'owner' | 'manager' | 'staff' | 'outlet';

export interface Category {
  id: number;
  created_at: string;
  name: string;
  description?: string;
}

// Removed Location Interface

export interface Supplier {
  id: number;
  created_at: string;
  name: string;
  contact_person?: string;
  phone?: string;
  email?: string;
  notes?: string;
}

// Updated Outlet Interface with Permissions
export interface OutletPermissions {
  dashboard: boolean;
  inventory_items: boolean;
  incoming_stock: boolean;
  outgoing_stock: boolean;
  opname: boolean;
  calculator: boolean;
  reports: boolean;
  manage_outlets?: boolean; // New: Permission to manage other outlets
  allowed_outlet_ids?: number[]; // New: List of specific outlet IDs allowed
}

export interface Outlet {
  id: number;
  created_at: string;
  name: string;
  address?: string;
  manager_name?: string; // PIC Name
  phone?: string;
  email?: string; // PIC Email
  is_active: boolean;
  login_username?: string;
  permissions?: OutletPermissions; // JSONB column
}

export interface Item {
  id: number;
  created_at: string;
  name: string;
  sku?: string;
  category_id: number;
  unit: string;
  purchase_unit?: string;
  conversion_to_base?: number;
  cost_price: number;
  selling_price?: number; // Added Selling Price
  min_stock: number;
  is_active: boolean;
  image_url?: string;
  // Joined data
  item_categories?: { name: string };
}

export interface OpnameSession {
  id: number;
  created_at: string;
  status: 'pending' | 'in_progress' | 'completed' | 'approved';
  created_by: string; // user id
  users?: { full_name: string }; // Joined data
}

export interface OpnameItem {
  id: number;
  session_id: number;
  item_id: number;
  // Removed location_id
  system_stock_at_start: number;
  physical_count: number | null;
  items: { name: string, sku: string, unit: string }; // Joined data
}

// --- PRODUCTION MODULE TYPES ---

export interface Recipe {
  id: number;
  target_item_id: number;
  name: string;
  description?: string;
  yield_quantity: number;
  yield_unit: string;
  is_active: boolean;
  // Joined
  items?: { name: string, sku: string }; // The finished good item
}

export interface RecipeIngredient {
  id: number;
  recipe_id: number;
  item_id: number;
  quantity: number;
  unit: string;
  // Joined
  items?: { name: string, cost_price: number, unit: string }; // The raw material
}

export interface ProductionOrder {
  id: number;
  created_at: string;
  recipe_id: number;
  quantity_to_produce: number;
  status: 'draft' | 'scheduled' | 'in_progress' | 'completed' | 'cancelled';
  scheduled_date: string;
  batch_number?: string;
  notes?: string;
  // Joined
  recipes?: { name: string, target_item_id: number };
}

// RPC Function return types
export interface DashboardMetrics {
  total_items: number;
  total_stock_value: number | null;
  active_locations: number; // Note: Might need DB update to remove this metric later
  low_stock_items_count: number;
}

export interface ReportRow {
  [key: string]: any;
}
