-- Create Recipes Table (Header)
CREATE TABLE IF NOT EXISTS recipes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  target_item_id BIGINT REFERENCES items(id) NOT NULL, -- The Finished Good
  name TEXT NOT NULL,
  description TEXT,
  yield_quantity NUMERIC DEFAULT 1, -- e.g., produces 10 bottles
  yield_unit TEXT, -- e.g., bottles
  is_active BOOLEAN DEFAULT TRUE
);

-- Create Recipe Ingredients Table (Details/BOM)
CREATE TABLE IF NOT EXISTS recipe_ingredients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipe_id BIGINT REFERENCES recipes(id) ON DELETE CASCADE NOT NULL,
  item_id BIGINT REFERENCES items(id) NOT NULL, -- The Raw Material
  quantity NUMERIC NOT NULL, -- Amount needed per yield
  unit TEXT NOT NULL
);

-- Create Production Orders Table
CREATE TABLE IF NOT EXISTS production_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  recipe_id BIGINT REFERENCES recipes(id) NOT NULL,
  quantity_to_produce NUMERIC NOT NULL, -- How many batches/units
  status TEXT CHECK (status IN ('draft', 'scheduled', 'in_progress', 'completed', 'cancelled')) DEFAULT 'draft',
  scheduled_date DATE DEFAULT CURRENT_DATE,
  start_time TIMESTAMPTZ,
  end_time TIMESTAMPTZ,
  assigned_to UUID REFERENCES auth.users(id), -- Chef/Staff
  notes TEXT,
  batch_number TEXT -- Auto-generated batch ID
);

-- Enable RLS
ALTER TABLE recipes ENABLE ROW LEVEL SECURITY;
ALTER TABLE recipe_ingredients ENABLE ROW LEVEL SECURITY;
ALTER TABLE production_orders ENABLE ROW LEVEL SECURITY;

-- Simple Policies (Adjust based on your RBAC needs)
CREATE POLICY "Enable read access for authenticated users" ON recipes FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable write access for authenticated users" ON recipes FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable update access for authenticated users" ON recipes FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Enable delete access for authenticated users" ON recipes FOR DELETE TO authenticated USING (true);

CREATE POLICY "Enable read access for authenticated users" ON recipe_ingredients FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable write access for authenticated users" ON recipe_ingredients FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable update access for authenticated users" ON recipe_ingredients FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Enable delete access for authenticated users" ON recipe_ingredients FOR DELETE TO authenticated USING (true);

CREATE POLICY "Enable read access for authenticated users" ON production_orders FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable write access for authenticated users" ON production_orders FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable update access for authenticated users" ON production_orders FOR UPDATE TO authenticated USING (true);
