-- =================================================================
-- FINAL CONSOLIDATED SCHEMA SCRIPT
-- This script resets and correctly builds the entire database schema.
-- It is designed to be run on a clean or inconsistent database.
-- =================================================================

-- =============================================
-- 1. CLEANUP PHASE
-- Drop existing objects in reverse order to avoid dependency errors.
-- =============================================
DROP TRIGGER IF EXISTS on_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();
DROP FUNCTION IF EXISTS public.get_item_stock(bigint);
DROP FUNCTION IF EXISTS public.get_item_stock_at_location(bigint, bigint);
DROP FUNCTION IF EXISTS public.update_timestamps();

DROP TABLE IF EXISTS public.stock_opname_items CASCADE;
DROP TABLE IF EXISTS public.stock_opname_sessions CASCADE;
DROP TABLE IF EXISTS public.stock_movements CASCADE;
DROP TABLE IF EXISTS public.items CASCADE;
DROP TABLE IF EXISTS public.suppliers CASCADE;
DROP TABLE IF EXISTS public.locations CASCADE;
DROP TABLE IF EXISTS public.item_categories CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;


-- =============================================
-- 2. TABLE CREATION PHASE
-- Create tables in the correct order of dependency.
-- =============================================

-- Users Table (Profile data linked to auth.users)
CREATE TABLE public.users (
    id uuid NOT NULL PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    full_name text,
    email text UNIQUE,
    role text NOT NULL DEFAULT 'staff'::text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);
COMMENT ON TABLE public.users IS 'Profile information for users.';

-- Item Categories Table
CREATE TABLE public.item_categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    description text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);
COMMENT ON TABLE public.item_categories IS 'Categories for inventory items (e.g., Ingredients, Beverages).';

-- Locations Table
CREATE TABLE public.locations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    type text DEFAULT 'warehouse'::text NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);
COMMENT ON TABLE public.locations IS 'Physical locations for stock (e.g., Bar, Kitchen, Warehouse).';

-- Suppliers Table
CREATE TABLE public.suppliers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    contact_person text,
    phone text,
    email text,
    notes text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);
COMMENT ON TABLE public.suppliers IS 'Information about suppliers.';

-- Items Table
CREATE TABLE public.items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    sku text UNIQUE,
    category_id bigint REFERENCES public.item_categories(id),
    unit text NOT NULL,
    purchase_unit text,
    conversion_to_base numeric,
    cost_price numeric NOT NULL DEFAULT 0,
    min_stock numeric NOT NULL DEFAULT 0,
    default_location_id bigint REFERENCES public.locations(id),
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);
COMMENT ON TABLE public.items IS 'Master list of all inventory items.';

-- Stock Movements Table (Event Sourcing)
CREATE TABLE public.stock_movements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id bigint NOT NULL REFERENCES public.items(id),
    location_id bigint NOT NULL REFERENCES public.locations(id),
    quantity_change numeric NOT NULL,
    movement_type text NOT NULL,
    reference_id text,
    note text,
    created_by uuid REFERENCES public.users(id),
    created_at timestamp with time zone DEFAULT now() NOT NULL
);
COMMENT ON TABLE public.stock_movements IS 'Append-only log of all stock changes.';

-- Stock Opname Sessions Table
CREATE TABLE public.stock_opname_sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status text NOT NULL DEFAULT 'pending'::text,
    notes text,
    created_by uuid NOT NULL REFERENCES public.users(id),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);
COMMENT ON TABLE public.stock_opname_sessions IS 'Header for a stock counting session.';

-- Stock Opname Items Table
CREATE TABLE public.stock_opname_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id bigint NOT NULL REFERENCES public.stock_opname_sessions(id) ON DELETE CASCADE,
    item_id bigint NOT NULL REFERENCES public.items(id),
    location_id bigint NOT NULL REFERENCES public.locations(id),
    system_stock_at_start numeric NOT NULL,
    physical_count numeric,
    notes text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    UNIQUE(session_id, item_id, location_id)
);
COMMENT ON TABLE public.stock_opname_items IS 'Line items for a specific stock opname session.';


-- =============================================
-- 3. FUNCTIONS AND TRIGGERS PHASE
-- =============================================

-- Function to automatically update 'updated_at' columns
CREATE OR REPLACE FUNCTION public.update_timestamps()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- Function to get total stock for an item across all locations
CREATE OR REPLACE FUNCTION public.get_item_stock(p_item_id bigint)
RETURNS numeric AS $$
BEGIN
    RETURN (SELECT COALESCE(SUM(quantity_change), 0) FROM public.stock_movements WHERE item_id = p_item_id);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- Function to get stock for an item at a specific location
CREATE OR REPLACE FUNCTION public.get_item_stock_at_location(p_item_id bigint, p_location_id bigint)
RETURNS numeric AS $$
BEGIN
    RETURN (SELECT COALESCE(SUM(quantity_change), 0) FROM public.stock_movements WHERE item_id = p_item_id AND location_id = p_location_id);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- Function to create a user profile when a new user signs up in Supabase Auth
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.users (id, full_name, email, role)
    VALUES (NEW.id, NEW.raw_user_meta_data->>'full_name', NEW.email, NEW.raw_user_meta_data->>'role');
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- Trigger to call handle_new_user on new user creation
CREATE TRIGGER on_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Apply timestamp triggers to all tables
CREATE TRIGGER set_users_timestamp BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE PROCEDURE public.update_timestamps();
CREATE TRIGGER set_item_categories_timestamp BEFORE UPDATE ON public.item_categories FOR EACH ROW EXECUTE PROCEDURE public.update_timestamps();
CREATE TRIGGER set_locations_timestamp BEFORE UPDATE ON public.locations FOR EACH ROW EXECUTE PROCEDURE public.update_timestamps();
CREATE TRIGGER set_suppliers_timestamp BEFORE UPDATE ON public.suppliers FOR EACH ROW EXECUTE PROCEDURE public.update_timestamps();
CREATE TRIGGER set_items_timestamp BEFORE UPDATE ON public.items FOR EACH ROW EXECUTE PROCEDURE public.update_timestamps();
CREATE TRIGGER set_stock_opname_sessions_timestamp BEFORE UPDATE ON public.stock_opname_sessions FOR EACH ROW EXECUTE PROCEDURE public.update_timestamps();
CREATE TRIGGER set_stock_opname_items_timestamp BEFORE UPDATE ON public.stock_opname_items FOR EACH ROW EXECUTE PROCEDURE public.update_timestamps();


-- =============================================
-- 4. ROW LEVEL SECURITY (RLS) PHASE
-- =============================================

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.item_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_opname_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_opname_items ENABLE ROW LEVEL SECURITY;

-- Policies for 'users' table
CREATE POLICY "Allow individual read access" ON public.users FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Allow individual update access" ON public.users FOR UPDATE USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

-- Policies for master data
CREATE POLICY "Allow authenticated read access" ON public.item_categories FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated write access" ON public.item_categories FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Allow authenticated read access" ON public.locations FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated write access" ON public.locations FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Allow authenticated read access" ON public.suppliers FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated write access" ON public.suppliers FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Allow authenticated read access" ON public.items FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated write access" ON public.items FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Policies for transactional data
CREATE POLICY "Allow authenticated read/write access" ON public.stock_movements FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated read/write access" ON public.stock_opname_sessions FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated read/write access" ON public.stock_opname_items FOR ALL TO authenticated USING (true) WITH CHECK (true);

COMMENT ON SCHEMA public IS 'Standard public schema for KopiStock application data';
