-- Create Outlets table for Production House distribution targets
create table if not exists public.outlets (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  address text,
  manager_name text,
  phone text,
  is_active boolean default true
);

-- Enable RLS
alter table public.outlets enable row level security;

-- Create policies (Assuming authenticated users can read/write for now)
create policy "Enable read access for authenticated users" on public.outlets
  for select using (auth.role() = 'authenticated');

create policy "Enable insert access for authenticated users" on public.outlets
  for insert with check (auth.role() = 'authenticated');

create policy "Enable update access for authenticated users" on public.outlets
  for update using (auth.role() = 'authenticated');

-- Add comments
comment on table public.outlets is 'List of internal outlets/branches for PT Artirasa Cipta Sentosa';
